# import * from './Operation.gql'
#import './CategoryFragment.gql'

mutation AccountCreate($description: String!, $operation: Operation!) {
  createCategory(description: $description, operation: $operation) {
    ...CategoryFragment
  }
}
