# import * from './Operation.gql'

query RecordsByMonth(
  $month: String
  $type: Operation
  $accountsId: [ID!]
  $categoriesId: [ID!]
) {
  records(
    month: $month
    type: $type
    accountsId: $accountsId
    categoriesId: $categoriesId
  ) {
    id
    type
    amount
    date
    description
    notes
    tags
    account {
      id
      description
    }
    category {
      id
      description
      operation
    }
    user {
      id
      name
    }
  }
}
