# import * from './Operation.gql'
#import './RecordsFragment.gql'
query RecordsByMonth(
  $month: String
  $type: Operation
  $accountsId: [ID!]
  $categoriesId: [ID!]
) {
  records(
    month: $month
    type: $type
    accountsId: $accountsId
    categoriesId: $categoriesId
  ) {
    ...RecordsFragment
  }
}
