# import * from './Operation.gql'
#import './RecordsFragment.gql'
mutation RecordCreate(
  $type: Operation!
  $amount: Float!
  $accountId: ID!
  $categoryId: ID!
  $date: Date!
  $description: String!
  $tags: String
  $notes: String
) {
  createRecord(
    type: $type
    amount: $amount
    accountId: $accountId
    categoryId: $categoryId
    date: $date
    description: $description
    tags: $tags
    notes: $notes
  ) {
    ...RecordsFragment
  }
}
